#TA signal analysis, evaluating the buy signals generated by technical indicators (RSI, MACD) for profitability

import pandas as pd

df = pd.read_csv('TA2.csv')

macd_data = df['MACD_signal']
rsi_data = df['RSI_signal']
time_data = df['date']
close_data = df['close']
low_data = df['Low']

ratio = []
# count = 0

def show(name, i, lst, price):
    print(f"{name} buy at", time_data[i])
    print(lst)
    print("BUY: ",low_data[i])
    print("MAX: ",max(price))
    print(low_data[i] < max(price))
    print(price)
    print("PROFIT: ",max(price)-low_data[i])
    ratio.append("Profit" if low_data[i] < max(price) else "Loss")
    print("\n")
  
def rsi(i):
  lst = list(macd_data[i-10:i])
  price = list(low_data[i+1:i+11])
  if "buy macd" in lst:
    show("RSI", i, lst, price)

def macd(i):
  lst = list(rsi_data[i-10:i])
  price = list(low_data[i+1:i+11 ])
  if "buy" in lst:
    show("MACD", i, lst, price)

for index in range(len(df)):
  if rsi_data[index] == "buy":
    rsi(index)
  if macd_data[index] == "buy macd":
    macd(index)

# print("Total Signals Processed: ", count)
print("Profitable Signals: ", ratio.count("Profit"))
print("Losing Signals: ", ratio.count("Loss"))
